baseurl = "http://maodanp.github.io/"
title = "Danping's Blog"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

# Pagination
paginate = 8
paginatePath = "page"

# Theme to use
theme = "hugo-bootstrap"

[taxonomies]
  tag = "tags"
  category = "categories"

# Google analytics
googleAnalytics = "UA-47268287-3"

# Languages

defaultContentLanguage = "en"

[languages.en]
  languageName = "English"

  [[languages.en.menu.main]]
    url = "/"
    name = "主页"
    weight = 1
  [[languages.en.menu.main]]
    url = "categories/技术志/"
    name = "技术志"
    weight = 2
  [[languages.en.menu.main]]
    url = "/categories/工具箱/"
    name = "工具箱"
    weight = 3
  [[languages.en.menu.main]]
    url = "categories/杂谈集/"
    name = "杂谈集"
    weight = 3
  [[languages.en.menu.main]]
    url = "/about/"
    name = "关于"
    weight = 4

# Links format

[permalinks]
  post = "/:year/:month/:title/"

[params]
  # Main sections (currently used for the recent posts in the sidebar)
  mainSections = ["post"]

  # Default author
  author = "Danping Mao"

  # Date format (default: Jan 2, 2006)
  # date_format = "Jan 2, 2006"

  # Display post summaries instead of content in list templates (default: true)
  # truncate = false

  [params.sidebar]
    # Weather to show the recent posts or not (default: true)
    # showRecent = false

    # Weather to show the taxonomies or not (default: true)
    # showTaxonomy = false

    # How many posts to show on the sidebar (Default: 5)
    # num_recent_posts = 5
